meta_title: "36 quai des aromes"
meta_description: "36 Quai Des Arômes est un jeu d'ambiance et de dégustation de vin. C'est un jeu d'enquête sur tablette et smartphone"
meta_image: "affichage.png" 
twitter_account: "@36quaidesaromes"